on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    outputs:
      apk_file: ${{ steps.find_apk.outputs.apk_path }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-core-${{ hashFiles('**/build.gradle.kts', '**/build.gradle', '**/libs.versions.toml') }}
          restore-keys: |
            gradle-deps

      - name: Cache Gradle Build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
            ~/.gradle/buildOutputCleanup/cache.properties
          key: gradle-builds-core-${{ github.sha }}
          restore-keys: |
            gradle-builds

      - name: Setup SDK
        run: |
          echo "ANDROID_HOME=${ANDROID_HOME}"
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}"
          mkdir -p "$ANDROID_HOME/licenses/"
          echo > "$ANDROID_HOME/licenses/android-sdk-license"
          echo -n 24333f8a63b6825ea9c5514f83c2829b004d1fee > "$ANDROID_HOME/licenses/android-sdk-license"
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.31.1"
          echo "sdk.dir=${ANDROID_HOME}" > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          echo "${{ secrets.SIGN_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
          ./gradlew :app:assembleRelease > build.log 2>&1
        env:
          KEYSTORE_PATH: "../keystore.jks"
          KEYSTORE_PASSWORD: ${{ secrets.SIGN_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}

      - name: Find APK file
        id: find_apk
        run: |
          apk_file=$(ls ./app/build/outputs/apk/release/*.apk | head -n 1)
          if [ -z "$apk_file" ]; then
            echo "❌ No APK file found!"
            exit 1
          fi
          echo "✅ APK file found: $apk_file"
          echo "apk_path=$apk_file" >> $GITHUB_ENV
          echo "apk_path=$apk_file" >> $GITHUB_OUTPUT

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk_file
          path: ${{ env.apk_path }}

      - name: Upload Build Log Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_log
          path: build.log

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: apk_file
          path: apk_artifact

      - name: Locate APK file
        id: locate_apk
        run: |
          apk_file=$(find apk_artifact -type f -name '*.apk' | head -n 1)
          if [ -z "$apk_file" ]; then
            echo "❌ No APK file found in artifact!"
            exit 1
          fi
          echo "✅ APK file located: $apk_file"
          echo "apk_file=$apk_file" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            ${{ steps.locate_apk.outputs.apk_file }}

      - name: Download Build Log Artifact
        uses: actions/download-artifact@v4
        with:
          name: build_log
          path: build_log

      - name: Rename and Upload Build Log to Release
        run: |
          cp build_log/build.log build_log_${{ github.sha }}.log

      - name: Upload Build Log to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: |
            build_log_${{ github.sha }}.log